### ISSUE TITLE
Wrong Forge Version Error

### ISSUE THREAD

**Issue by Roxamos** [TPPIC/Test-Pack-Please-Ignore-2C#1]
[2016-11-03-1.log.gz](https://github.com/TPPIC/Test-Pack-Please-Ignore-2C/files/568862/2016-11-03-1.log.gz)

**Comment by czbuendel** [comment]
Here is wrote this up because I was having the same problem. If you don't want to wait for an update this should get you up and running. 
1. Go to your TPPI 2 install directory. Open up "pack.json" and find "name": "net.minecraftforge:forge:1.7.10-10.13.4.####-1.7.10:universal" and change the #### to 1614.
2. Navigate to the bottom and locate "id": "1.7.10-Forge10.13.4.####-1.7.10:universal" and change #### to 1614.
3. Save the file.

This should get you good to go with starting the mod pack.

(Removed unnecessary part)

**Comment by Prospector** [comment]
May I ask if you are using the FTB Launcher or the Curse launcher?

**Comment by czbuendel** [comment]
I am using the FTB launcher

**Comment by czbuendel** [comment]
Apologies I didn't say that in the original post

**Comment by Roxamos** [comment]
I am using Curse launcher

Lee Clements

**Comment by m4sterP** [comment]
There was a small error in the upload process that made FTB (and thus also Curse) use 1558 instead of 1614, it will be fixed soon™. You can easily change the Forge version in the Curse Launcher btw. Just open the page of the downloaded mod pack, press "..." in the top right corner, press "profile options", untick "Locked" and then change the Modloader version to 1614 a few lines below.

**Comment by Roxamos** [comment]
Thank you. I'm new to modded Minecraft

Lee Clements

**Comment by mantoos** [comment]
@czbuendel I followed your instructions step by step. It doesn't work for me. The FTB Launcher tries five time to "Checking local assets file, for MC version 1.7.10 Please Wait!" (the new jar-File of .1614) with the result of "Error occured during downloading the assets", and nothing more happens.

One question to Step 8: I have version 345 (####); I don't see any version greater than that in your download suggestion. Any suggestions to this and above? Thank you!

**Comment by Prospector** [comment]
We have asked for the forge version to be updated, so hopefully later tonight there will be an update to fix it.

**Comment by czbuendel** [comment]
@mantoos Version 345 works as it is the one that I was using. 

As for FTB saying an error downloading assets, All I could find is that is about something to do with antivirus software blocking FTB from downloading certain files.

**Comment by czbuendel** [comment]
@mantoos it would be best to just force FTB launcher to just re-download the pack and just change the forge file it references in Steps 1 & 2. You should be good to go after that.

**Comment by mantoos** [comment]
@czbuendel Thanks for your reply. Your previous download link of version 1614 was acutally a download link to a forge version of 1.10.2. I updated from 1558 to 1614 now and the launcher is starting TPPI2 again. But Forge now has complains about over 200 missing blocks by loading my save. Should be no harm answering "Yes"?

**Comment by czbuendel** [comment]
@mantoos 
It's from forestry correct?

I was getting the same when I was loading a save from 0.2.6 but it is probably because Forestry was updated.

**Comment by Prospector** [comment]
Make sure to backup your world first before any time you update.

**Comment by Prospector** [comment]
1.0.1 was pushed, updating forge.
